spring.datasource.url=jdbc:postgresql://localhost:5432/payguarddb
spring.datasource.username=payguard
spring.datasource.password=payguard

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.h2.console.enabled=false